export const POS = {
  TITLE: 'POS Cajero',
  SUBTITLE: 'Crear pedidos en establecimiento',
  LAST_ORDER: 'Ultimo:',
  SEARCH_PLACEHOLDER: 'Buscar producto...',
  ALL_CATEGORIES: 'Todos',
  NO_PRODUCTS: 'No se encontraron productos',
  CURRENT_ORDER: 'Pedido Actual',
  CLEAR: 'Limpiar',
  EMPTY_CART: 'Toca un producto para agregarlo',
  NOTES_PLACEHOLDER: 'Notas del pedido (opcional)',
  CASH: 'Efectivo',
  TRANSFER: 'Transfer.',
  TOTAL: 'Total:',
  CREATE_ORDER: 'Crear Pedido',
  CONFIRM_TITLE: 'Confirmar Pedido',
  CONFIRM_TYPE_LABEL: 'Tipo:',
  CONFIRM_TYPE_VALUE: 'En establecimiento',
  CONFIRM_PAYMENT_LABEL: 'Pago:',
  CONFIRM_PAYMENT_CASH: 'Efectivo',
  CONFIRM_PAYMENT_TRANSFER: 'Transferencia',
  CONFIRM_TOTAL: 'Total',
  CANCEL: 'Cancelar',
  CONFIRM: 'Confirmar',
  TOAST_SUCCESS: (n: number) => `Pedido #${n} creado exitosamente`,
  TOAST_EMPTY: 'Agrega productos al pedido',
} as const;
